### PR TITLE
Further improvement of system monitor functionality for autoware (migrating from gitlab)

### PR DESCRIPTION
**Pull request by ito-san**
***Migrated from gitlab to github according to https://gitlab.com/autowarefoundation/autoware.ai/utilities/-/merge_requests/74#note_363222441.***

### Description

System monitor detects hardware errors such as CPU high temperature, high usage,etc. which might make system unstable.<br>
Upon the detection of such errors, vehicle should be stopped safely in autonomous driving.<br>
This can be realized by using system monitor, diagnostic aggregator, and emergency handler.<br>
*  System monitor: [ethz-asl/ros-system-monitor](https://github.com/ethz-asl/ros-system-monitor)
*  Diagnostic aggregator: http://wiki.ros.org/diagnostic_aggregator
*  Emergency handler: https://gitlab.com/autowarefoundation/autoware.ai/common/-/merge_requests/40

Some projects maybe use ros-system-monitor(this is made by python, some bugs exist in th code) and change it as you like.<br>
However, this tool was originally developed for robotics, not for autonomous driving which safety is required,<br>
and I'm afraid that unfortunately the repository has not been maintained for a long time.<br>
I would like to help maintain the functionality of software and make the failsafe framework usable easily by including system monitor into autoware.

In addition, C++ object is deterministic and object lifetime can be designed by user, so this helps to eliminate garbage collection which impacts system performance.<br>
Also C++ can process in faster speed and more real-time than python, this helps to stop the vehicle properly and safely in an emergency situation.

### Implementation considerations

1. Rewrite python code in C++.
2. Some bug fixes.(Unable to get CPU temperature for each core, CPU monitor not work properly in Japanese environment, etc.)
3. Add to support some architectures. (CPU monitor only supports intel architecture, this is not designed for ARM.)
4. Add detection of thermal throttling.
5. Add GPU monitor. (GPU Temperature, GPU Clocks Throttle Reasons, GPU Utilization, etc.)
6. Add Process Monitor. (High-load Proc, High-mem Proc)

### Additional information

*  Remaining works<br>
   ~~Detection of CPU & GPU thermal throttling event on tegra platform.~~

### Implementation description

Please refer to: 
*  [README](https://github.com/ito-san/utilities/blob/feature/system_monitor/system_monitor/README.md)
*  [Class diagrams](https://github.com/ito-san/utilities/blob/feature/system_monitor/system_monitor/docs/class_diagrams.md)
*  [Sequence diagrams](https://github.com/ito-san/utilities/blob/feature/system_monitor/system_monitor/docs/seq_diagrams.md)

### CODE REVIEW

**Comment by JWhitleyWork** [comment]
@ito-san Can you please re-base this on `master`? CI should complete successfully now since a new cross-compilation container is available.

**Comment by ito-san** [comment]
> @ito-san Can you please re-base this on `master`? CI should complete successfully now since a new cross-compilation container is available.

No problem. Done.

**Comment by JWhitleyWork** [comment]
@ito-san I'm not sure exactly what happened but your fork's `master` got out of sync with ours (it shows that it is 29 commits ahead). Assuming you have not made any changes to your `master` branch and are instead working on your `feature/system_monitor` branch, you should be able to do the following to clear it up (on your local repo):

```
git remote add upstream https://github.com/Autoware-AI/utilities.git
git fetch upstream
git checkout -b fix-master upstream/master
git branch -D master
git checkout -b master
git push -f --set-upstream origin master
```

This should align your `master` branch with ours. You should then be able to rebase your `feature/system_monitor` branch on your `master` branch and force-push it. You'll have to delete the `.gitlab-ci.yml` file a few times during this rebase.

I tested the above commands on a fork of your fork and it worked correctly.

**Comment by ito-san** [comment]
Thank you for your feedback. I'm also not sure what happened, and followed your instructions.
Then I performed the following commands .

```
git checkout feature/system_monitor 
git rebase master
rm .gitlab-ci.yml
git push -f origin feature/system_monitor 
```
Should I start over?

**Comment by JWhitleyWork** [comment]
>Should I start over?

No, it looks good now! I'll review it soon.

**Comment by ito-san** [comment]
@JWhitleyWork Thank you so much for your review! I deleted the branch and fork.

**Pull request merged**
